### ISSUE TITLE
Is this project still maintained? 

### ISSUE THREAD

**Issue by uthng** [octaltree/playwright-rust#30]
Hi,

I would like to use playwright with rust in my project. When searching, I found thks repository. But it seems that there hasnot been updated for a while. So, I would like to know if this project is still maintained? If  yes, does it work with the latest version of Playwright? 

Best regards

NT

**Comment by octaltree** [comment]
Good question. It works fine as long as the test passes, but I do not recommend it for production.

I have been unable to generate the necessary effort to follow up recently.
Now that rust--headless-chrome is active by new maintainer, there is also the option of chromiumoxide.

**Comment by Randall-Coding** [comment]
> Good question. It works fine as long as the test passes, but I do not recommend it for production.
> 
> I have been unable to generate the necessary effort to follow up recently. Now that rust--headless-chrome is active by new maintainer, there is also the option of chromiumoxide.

@octaltree What would you estimate the level of time commitment needed to upgrade playwright driver from 1.11 to 1.20.2?  I am willing to help out with that as I need the new driver features to upload large files and that was fixed in a PR a few months ago https://github.com/microsoft/playwright/pull/12937.

Thoughts on the feasibility of that?

**Comment by jtomek** [comment]
I would be interested in this too. 

Have you considered turning on donations to help you maintain this package?

**Comment by octaltree** [comment]
I've started supporting 1.25 in dev branch, I can't say for sure because I're still investigating.

**Comment by Randall-Coding** [comment]
> I've started supporting 1.25 in dev branch, I can't say anything about it because it's under investigation.

Hey that's awesome @octaltree .  Btw I just hired someone to look into this too and help with the upgrade.  Perhaps you'd be interested in working with him?  This is his handle @tmahmood

**Comment by jtomek** [comment]
This is the best piece of news this week! 

I'd like to see a donate button somewhere.

**Comment by octaltree** [comment]
We can now use src/protocol/protocol.yml for interaction with the playwright server. Previously we had to read the original source.
I have written a process in scripts/src/generate_protocol.rs to generate that schema as a type of rust. If you could help me, I would be very grateful.
The api and implementation will be prioritized and the protocol part will come later, so pull requests are welcome!

**Comment by tmahmood** [comment]
Hi @octaltree, glad that you are working on the project again :)

I have been studying the library for a while. Initial problem is the `InitializationError`, With the help of @Randall-Coding, I've found, the problem is, after starting the driver, we need to send an `initialize` message to it. The device list is returned as response. Previously, it was output to the stdin immediately after run-driver start.

Can you provide me an idea, guideline, how can I send this initial message? Or are you working on this already?

**Comment by octaltree** [comment]
I am not familiar with the specific errors you are facing with 1.24.2. Sorry.
The latest commit sends an initialize request and creates a Playwright instance from the response. In 1.11, I have a similar implementation that reads the output of the driver and the microsoft client. Now that the schema for sending requests has been clarified, it may be possible to use it.

https://github.com/microsoft/playwright-python/blob/ab6bea1ef1c2358440835b866b98bb5b479139e3/playwright/async_api/_context_manager.py#L46
https://github.com/microsoft/playwright-python/blob/ab6bea1ef1c2358440835b866b98bb5b479139e3/playwright/_impl/_connection.py#L222
https://github.com/microsoft/playwright-python/blob/ab6bea1ef1c2358440835b866b98bb5b479139e3/playwright/_impl/_connection.py#L164

That's all I can say right now.

**Comment by tmahmood** [comment]
Thank you very much for your response. 

I am trying with the latest alpha version you are using now in the dev branch. Are you able to run tests? For me because of the `InitializationError`, playwright-rust seems to be not working.

I am able to send request to playwright server now. But I am receiving this error:

Request received by playwright
```
{ guid: '0', method: 'initialize', param: { sdkLanguage: 'rust' } }
```
Error I am getting
```
{"error":{"error":{"message":"Target page, context or browser has been closed","stack":"Error: Target page, context or browser has been closed\n    at DispatcherConnection.dispatch (/home/mahmood/.cache/ms-playwright/playwright-rust/1.25.0-alpha-jul-26-2022/package/lib/server/dispatchers/dispatcher.js:298:49)\n    at PipeTransport.transport.onmessage (/home/mahmood/.cache/ms-playwright/playwright-rust/1.25.0-alpha-jul-26-2022/package/lib/cli/driver.js:63:26)\n    at Immediate._onImmediate (/home/mahmood/.cache/ms-playwright/playwright-rust/1.25.0-alpha-jul-26-2022/package/lib/protocol/transport.js:89:34)\n    at processImmediate (node:internal/timers:466:21)","name":"Error"}}}
```

I'll be digging in more, if you have anything that would shade light on the issue, it will be much appreciated :)

**Comment by satvikpendem** [comment]
I haven't seen any commits this year, I do see some PRs (https://github.com/octaltree/playwright-rust/pull/51), but it doesn't look like the author, @SamuelMarks, actually has write access so they can't actually merge any PRs, is the project still maintained in 2023?

**Comment by NinoSkopac** [comment]
Guess not

**Comment by coopbri** [comment]
Hi all, just curious if there is an active fork of this? If not, I would gladly support this under https://github.com/omnidotdev, where my team and I are building an ecosystem of FOSS software (you'll notice the org is pretty barren as far as public repos go at the moment, we are launching our first FOSS product in 2025). If there is consensus on this, let me know and I can work to get it forked and in good hands. We use both Rust and Playwright and I would love to see this awesome project get the love and care it needs!

**Comment by satvikpendem** [comment]
@coopbri sounds good, would love to see it

**Comment by coopbri** [comment]
> @coopbri sounds good, would love to see it

Sure thing! I just performed the migration (fork) and have been working on an upgrade to the latest Playwright version (v1.49.x), based on the original work from @tmahmood (https://github.com/octaltree/playwright-rust/pull/49) and @SamuelMarks (https://github.com/octaltree/playwright-rust/pull/51) (thank you both). You can see this pending work at https://github.com/omnidotdev/playwright-rust/tree/feature/1.49.

I might need help with this upgrade, as I am just now getting a feel for the repository and how it is set up. If anyone has insight or can contribute, that is very welcome. It's getting close, but there are some pending issues with the API (particularly device descriptors issues at runtime). All code and processes will be documented to the best of my ability.

**Comment by yuchanns** [comment]
@coopbri Hi I see you archived the repository. Wondering what happens

**Comment by coopbri** [comment]
> [@coopbri](https://github.com/coopbri) Hi I see you archived the repository. Wondering what happens

Hey, it ended up not being worth the effort as you can easily write tests alongside your Rust code in a Microsoft-supported language or use chromiumoxide or similar. See the note in https://github.com/omnidotdev/playwright-rust/blob/master/README.md

If there is strong community interest and help, we might pick this project back up again, but it is a huge undertaking for little gain.

**Comment by SamuelMarks** [comment]
Similarly I'm awaiting any show of interest from anyone [preferably commercial] in order to maintain a new playwright-rust
